export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const LOGIN_REQUEST = "LOGIN_REQUEST";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOGOUT = "LOGOUT";

export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const DEPOSIT_SUCCESS = "DEPOSIT_SUCCESS";
export const DEPOSIT_FAIL = "DEPOSIT_FAIL";

export const WITHDRAWAL_SUCCESS = "WITHDRAWAL_SUCCESS";
export const WITHDRAWAL_FAIL = "WITHDRAWAL_FAIL";

export const TRANSFER_SUCCESS = "TRANSFER_SUCCESS";
export const TRANSFER_FAIL = "TRANSFER_FAIL";

export const GET_BALANCE_SUCCESS = "GET_BALANCE_SUCCESS";
export const GET_BALANCE_FAILED = "GET_BALANCE_FAILED";

export const OPEN_DEPOSIT_MODAL = "OPEN_DEPOSIT_MODAL";
export const OPEN_WITHDRAW_MODAL = "OPEN_WITHDRAW_MODAL";
export const OPEN_TRANSFER_MODAL = "OPEN_TRANSFER_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";

export const CLEAR_ERROR = "CLEAR_ERROR";
